#!/usr/bin/env python3
"""
New representation controls for DLP grokking experiments.

Implements:
  R2: PERMUTED_CRT  — separate per-factor permutations
  R3: RANDOM_BIJECTION — global random bijection destroying factor membership
  R4: MIXED_RADIX   — non-algebraic two-coordinate system
  R5: RANDOM_SINGLE — single-channel random permutation

These are encoding functions compatible with mi_suite.py.
"""

import random
from typing import Dict, Tuple, List
import numpy as np


def generate_permuted_crt_maps(p: int, a: int, b: int, seed: int = 42) -> Dict:
    """Generate separate per-factor permutations for R2: PERMUTED_CRT."""
    rng = random.Random(seed)
    # Permutation for factor A (order-a subgroup, a elements)
    perm_a = list(range(a))
    rng.shuffle(perm_a)
    # Permutation for factor B (order-b subgroup, b elements)
    perm_b = list(range(b))
    rng.shuffle(perm_b)
    return {"perm_a": perm_a, "perm_b": perm_b}


def generate_random_bijection(p: int, a: int, b: int, seed: int = 42) -> Dict:
    """Generate random bijection G -> Z_a x Z_b for R3: RANDOM_BIJECTION.

    This destroys factor membership: elements are randomly assigned to
    (A, B) coordinate pairs with no relationship to CRT factors.
    """
    rng = random.Random(seed)
    # N = p - 1 elements in the group
    N = p - 1
    # Generate all possible (r_a, r_b) pairs
    pairs = [(i % a, i % b) for i in range(N)]
    # Shuffle the pairs
    rng.shuffle(pairs)
    # Map each group element (indexed 0..N-1) to a random pair
    bijection = {i: pairs[i] for i in range(N)}
    return {"bijection": bijection, "a": a, "b": b}


def generate_mixed_radix_map(p: int, a: int, b: int, seed: int = 42) -> Dict:
    """Generate mixed-radix mapping for R4: MIXED_RADIX.

    Uses enumeration of group elements by sorted order (NOT by exponent x).
    j(y) = index of y in sorted list of group elements
    q = floor(j / b), r = j mod b
    """
    # Generate all group elements
    N = p - 1
    # Find primitive root
    from mi_suite import _is_primitive_root
    g = None
    for candidate in range(2, p):
        if _is_primitive_root(candidate, p):
            g = candidate
            break

    # Enumerate group elements by sorted order (NOT by exponent)
    elements = sorted(range(1, p))  # all nonzero residues
    # Map each element to its index
    elem_to_idx = {y: i for i, y in enumerate(elements)}

    return {"g": g, "elem_to_idx": elem_to_idx, "a": a, "b": b, "p": p}


def generate_random_single_map(p: int, seed: int = 42) -> Dict:
    """Generate random permutation for R5: RANDOM_SINGLE."""
    rng = random.Random(seed)
    perm = list(range(p))
    rng.shuffle(perm)
    return {"perm": perm}


def encode_r2_permuted_crt(g: int, h: int, x: int, p: int, a: int, b: int,
                            maps: Dict) -> Tuple[List[int], int]:
    """R2: PERMUTED_CRT encoding."""
    from mi_suite import project_factor, INT_OFFSET, BOS, SEP, EOS

    g_a = project_factor(g, p, a)
    g_b = project_factor(g, p, b)
    h_a = project_factor(h, p, a)
    h_b = project_factor(h, p, b)

    # Apply per-factor permutations
    # The subgroup of order a has elements that are a-th roots of unity
    # We need to map each root to its index in the subgroup, then permute
    # For simplicity, we use the value directly as index (since subgroup
    # elements are distinct mod p, but we need to map to 0..a-1)

    # Actually, the projection g_a = g^{(p-1)/a} takes values in a subgroup
    # of order a. The values are specific residues mod p. We need to:
    # 1. Map each subgroup element to its index (0..a-1)
    # 2. Apply the permutation
    # 3. Map back to a subgroup element

    # For the order-a subgroup generated by g_a, the elements are:
    # {g_a^0, g_a^1, ..., g_a^{a-1}} = {1, g_a, g_a^2, ...}
    # We need a lookup from value to index

    # Build subgroup element lists
    sub_a = [pow(g_a, i, p) for i in range(a)]  # order-a subgroup elements
    sub_b = [pow(g_b, i, p) for i in range(b)]  # order-b subgroup elements

    # Map from value to index
    val_to_idx_a = {v: i for i, v in enumerate(sub_a)}
    val_to_idx_b = {v: i for i, v in enumerate(sub_b)}

    # Apply permutation
    perm_a = maps["perm_a"]
    perm_b = maps["perm_b"]

    # Get indices, permute, map back
    idx_g_a = val_to_idx_a[g_a]
    idx_g_b = val_to_idx_b[g_b]
    idx_h_a = val_to_idx_a[h_a]
    idx_h_b = val_to_idx_b[h_b]

    s_g_a = sub_a[perm_a[idx_g_a]]
    s_g_b = sub_b[perm_b[idx_g_b]]
    s_h_a = sub_a[perm_a[idx_h_a]]
    s_h_b = sub_b[perm_b[idx_h_b]]

    def tok(val: int) -> int:
        return val + INT_OFFSET

    tokens = [BOS, tok(s_g_b), SEP, tok(s_g_a), SEP, tok(s_h_b), SEP, tok(s_h_a), EOS]
    target = tok(x)
    return tokens, target


def encode_r3_random_bijection(g: int, h: int, x: int, p: int, a: int, b: int,
                                maps: Dict) -> Tuple[List[int], int]:
    """R3: RANDOM_BIJECTION encoding.

    Randomly assigns group elements to (A, B) coordinate pairs.
    Destroys factor membership.
    """
    from mi_suite import INT_OFFSET, BOS, SEP, EOS

    bijection = maps["bijection"]

    # Map g and h to their indices in the group (by exponent)
    # We need to find the exponent of g and h
    # Actually, the bijection maps group element index -> (r_a, r_b)
    # We need to index group elements consistently

    # The bijection was built with indices 0..N-1 where N = p-1
    # We need to map each group element y to its index
    # Use the discrete log as index: index = x where y = g^x
    # But we don't know x for arbitrary y...

    # Actually, for the bijection to work, we need a consistent enumeration
    # of group elements. Let's use sorted order of elements.
    elements = sorted(range(1, p))
    elem_to_idx = {y: i for i, y in enumerate(elements)}

    idx_g = elem_to_idx[g]
    idx_h = elem_to_idx[h]

    r_a_g, r_b_g = bijection[idx_g]
    r_a_h, r_b_h = bijection[idx_h]

    def tok(val: int) -> int:
        return val + INT_OFFSET

    tokens = [BOS, tok(r_b_g), SEP, tok(r_a_g), SEP, tok(r_b_h), SEP, tok(r_a_h), EOS]
    target = tok(x)
    return tokens, target


def encode_r4_mixed_radix(g: int, h: int, x: int, p: int, a: int, b: int,
                           maps: Dict) -> Tuple[List[int], int]:
    """R4: MIXED_RADIX encoding.

    Uses sorted-order enumeration of group elements, then mixed-radix split.
    No algebraic relationship to CRT.
    """
    from mi_suite import INT_OFFSET, BOS, SEP, EOS

    elem_to_idx = maps["elem_to_idx"]
    b_val = maps["b"]

    idx_g = elem_to_idx[g]
    idx_h = elem_to_idx[h]

    q_g = idx_g // b_val
    r_g = idx_g % b_val
    q_h = idx_h // b_val
    r_h = idx_h % b_val

    def tok(val: int) -> int:
        return val + INT_OFFSET

    tokens = [BOS, tok(q_g), SEP, tok(r_g), SEP, tok(q_h), SEP, tok(r_h), EOS]
    target = tok(x)
    return tokens, target


def encode_r5_random_single(g: int, h: int, x: int, p: int,
                              maps: Dict) -> Tuple[List[int], int]:
    """R5: RANDOM_SINGLE encoding."""
    from mi_suite import INT_OFFSET, BOS, SEP, EOS

    perm = maps["perm"]

    s_g = perm[g]
    s_h = perm[h]

    def tok(val: int) -> int:
        return val + INT_OFFSET

    tokens = [BOS, tok(s_g), SEP, tok(s_h), EOS]
    target = tok(x)
    return tokens, target


# Encoding wrapper for mi_suite compatibility
def encode_representation(g: int, h: int, x: int, variant: str,
                          p: int = 113, crt_factors: Tuple[int, int] = None,
                          maps: Dict = None) -> Tuple[List[int], int]:
    """Unified encoding function supporting all representations."""
    if crt_factors is None:
        from mi_suite import coprime_factorization
        a, b = coprime_factorization(p - 1)
    else:
        a, b = crt_factors

    if variant in ("RAW", "standard", "CRT-BOTH", "CRT-7", "CRT-16",
                    "RAW+CRT", "SCRAMBLED"):
        return encode_crt_representation_compat(g, h, x, variant, p, crt_factors, maps)
    elif variant == "PERMUTED_CRT":
        return encode_r2_permuted_crt(g, h, x, p, a, b, maps)
    elif variant == "RANDOM_BIJECTION":
        return encode_r3_random_bijection(g, h, x, p, a, b, maps)
    elif variant == "MIXED_RADIX":
        return encode_r4_mixed_radix(g, h, x, p, a, b, maps)
    elif variant == "RANDOM_SINGLE":
        return encode_r5_random_single(g, h, x, p, maps)
    else:
        raise ValueError(f"Unknown variant: {variant}")


def encode_crt_representation_compat(g: int, h: int, x: int, variant: str,
                                     p: int, crt_factors, maps: Dict = None):
    """Compatibility wrapper for original representations."""
    from mi_suite import encode_crt_representation
    if variant == "SCRAMBLED" and maps is None:
        # Generate default scramble map
        rng = random.Random(12345)
        perm = list(range(p))
        rng.shuffle(perm)
        maps = {"scramble_map": {i: perm[i] for i in range(p)}}

    if variant == "SCRAMBLED":
        # Use the scramble map from maps
        from mi_suite import project_factor, INT_OFFSET, BOS, SEP, EOS
        a, b = crt_factors
        g_a = project_factor(g, p, a)
        g_b = project_factor(g, p, b)
        h_a = project_factor(h, p, a)
        h_b = project_factor(h, p, b)
        sm = maps["scramble_map"]
        s_g_b = sm.get(g_b, g_b)
        s_g_a = sm.get(g_a, g_a)
        s_h_b = sm.get(h_b, h_b)
        s_h_a = sm.get(h_a, h_a)
        def tok(val): return val + INT_OFFSET
        tokens = [BOS, tok(s_g_b), SEP, tok(s_g_a), SEP, tok(s_h_b), SEP, tok(s_h_a), EOS]
        target = tok(x)
        return tokens, target
    else:
        return encode_crt_representation(g, h, x, variant, p, crt_factors)


if __name__ == "__main__":
    # Test the encodings
    p = 113
    a, b = 7, 16

    # Generate maps
    r2_maps = generate_permuted_crt_maps(p, a, b, seed=42)
    r3_maps = generate_random_bijection(p, a, b, seed=42)
    r4_maps = generate_mixed_radix_map(p, a, b, seed=42)
    r5_maps = generate_random_single_map(p, seed=42)

    # Test with a specific triple
    g, h, x = 3, 50, 30  # example triple

    print("R2 (PERMUTED_CRT):", encode_r2_permuted_crt(g, h, x, p, a, b, r2_maps))
    print("R3 (RANDOM_BIJECTION):", encode_r3_random_bijection(g, h, x, p, a, b, r3_maps))
    print("R4 (MIXED_RADIX):", encode_r4_mixed_radix(g, h, x, p, a, b, r4_maps))
    print("R5 (RANDOM_SINGLE):", encode_r5_random_single(g, h, x, p, r5_maps))

    # Verify invertibility
    print("\n=== Invertibility Check ===")

    # R3: Check that bijection is a bijection
    bij = r3_maps["bijection"]
    pairs = list(bij.values())
    unique_pairs = set(pairs)
    print(f"R3: {len(pairs)} pairs, {len(unique_pairs)} unique (should be {p-1})")

    # R4: Check that mixed radix is invertible
    elem_to_idx = r4_maps["elem_to_idx"]
    print(f"R4: {len(elem_to_idx)} elements mapped (should be {p-1})")
